# Generated by Django 5.2 on 2025-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('official_packaging_images', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
