# Generated by Django 5.2 on 2025-05-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_remove_medicine_official_packaging_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='barcode',
        ),
    ]
