# Generated by Django 5.2 on 2025-05-01 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin_dist', 'Admin/Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('consumer', 'Consumer')], default='consumer', max_length=20),
        ),
    ]
